"""FastAPI application. Serves the API and the single-page frontend.

Interactive API documentation is at /docs, generated by FastAPI from the type hints.
"""
import os

# onnxruntime tries to pin thread affinity and fails inside a container, printing an
# alarming red error that is not one. Asking for a fixed thread count avoids it.
os.environ.setdefault("OMP_NUM_THREADS", "2")

from fastapi import FastAPI
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

from . import config, rag, store
from .data import load_courses

app = FastAPI(
    title="Course Materials RAG",
    description="Ask questions about course materials. Retrieval-augmented generation "
                "over a local vector store, with a small local language model.",
    version="1.0.0",
)


class ChatRequest(BaseModel):
    question: str
    session_id: str | None = None


class Source(BaseModel):
    course: str
    lesson_number: int
    lesson_title: str
    link: str


class ChatResponse(BaseModel):
    answer: str
    sources: list[Source]
    session_id: str


@app.post("/api/chat", response_model=ChatResponse)
def chat(req: ChatRequest):
    """Answer a question from the indexed course material, citing which lessons were used."""
    return rag.answer(req.question, req.session_id)


@app.get("/api/courses")
def courses():
    """List the indexed courses and their lessons."""
    return [
        {
            "title": c["title"],
            "instructor": c["instructor"],
            "link": c["link"],
            "lessons": [{"number": l["number"], "title": l["title"]} for l in c["lessons"]],
        }
        for c in load_courses()
    ]


@app.get("/api/stats")
def stats():
    """Corpus and index statistics."""
    cs = load_courses()
    lessons = sum(len(c["lessons"]) for c in cs)
    chars = sum(len(l["content"]) for c in cs for l in c["lessons"])
    try:
        chunks = store.get_collection().count()
    except Exception:
        chunks = 0
    return {
        "courses": len(cs),
        "lessons": lessons,
        "characters": chars,
        "indexed_chunks": chunks,
        "chunk_size": config.CHUNK_CHARS,
        "top_k": config.TOP_K,
        "backend": config.LLM_BACKEND,
        "model": config.LOCAL_MODEL if config.LLM_BACKEND == "local" else config.LLM_MODEL,
        "active_sessions": len(rag.SESSIONS),
    }


@app.get("/api/session/{session_id}")
def session(session_id: str):
    """The conversation history held for one session."""
    return {"session_id": session_id, "turns": rag.history(session_id)}


app.mount("/static", StaticFiles(directory="static"), name="static")


@app.get("/")
def index():
    return FileResponse("static/index.html")
